name: Fluxo de Trabalho
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm install

    - name: Definir variáveis de ambiente
      run: |
        echo "URL=${{ secrets.URL }}" >> $GITHUB_ENV
        echo "SUBSCRIPTION_KEY=${{ secrets.SUBSCRIPTION_KEY }}" >> $GITHUB_ENV
        echo "SUBSCRIPTION_REGION=${{ secrets.SUBSCRIPTION_REGION }}" >> $GITHUB_ENV

    - name: Executar script
      run: node src/js/script.js
      continue-on-error: true

    - name: Notificar sobre falha
      if: ${{ failure() }}
      run: echo "O script falhou. Verifique os logs para mais detalhes."
